CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL,
  "email" varchar(30) NOT NULL,
  "age" int NOT NULL,
  "role_id" int NOT NULL
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(15) NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(50) NOT NULL,
  "description" varchar(150),
  "level" varchar(20) NOT NULL,
  "teacher_id" int NOT NULL,
  "category_id" int NOT NULL
);

CREATE TABLE "courses_students" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" int,
  "courses_id" int
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) NOT NULL
);

CREATE TABLE "course_video" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) NOT NULL,
  "url" varchar(150) NOT NULL,
  "courses_id" int NOT NULL
);

ALTER TABLE "courses" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "course_video" ADD FOREIGN KEY ("courses_id") REFERENCES "courses" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("teacher_id") REFERENCES "users" ("id");

ALTER TABLE "courses_students" ADD FOREIGN KEY ("student_id") REFERENCES "users" ("id");

ALTER TABLE "courses_students" ADD FOREIGN KEY ("courses_id") REFERENCES "courses" ("id");


INSERT INTO roles (name) VALUES ('student'),('teacher'), ('admin');
INSERT INTO categories (name) VALUES ('Ciencias'),('Arte'),('Historia');
INSERT INTO users (name, email, age, role_id) VALUES ('Felipe Grillo', 'ing.felipegrillo@gmail.com', 36, 3), ('Ian Rosas', 'ianrosas@gmail.com', 32, 2);
INSERT INTO courses (title, description,level,teacher_id,category_id) VALUES ('Historia de los mundiales', 'Resumen de la historia de todas las copas del mundo', 'advanced', 2, 3);
INSERT INTO course_video (title, url, courses_id) VALUES ('Pinturas modernas', 'http//:pinturasmodernas.com',1) , ('Los mejores goles mundiales','http//:losmejoresgolesmundiales.com',2);
INSERT INTO courses_students (student_id, courses_id) VALUES (1,1), (1,2);


SELECT * FROM roles;
SELECT * FROM categories;
SELECT * FROM users;
SELECT * FROM courses;
SELECT * FROM course_video;
SELECT * FROM courses_students;